name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Successful validation
        id: test-action--success
        uses: ./
        with:
          include: ./__tests__/fixtures/valid/*

      - name: Find error in config
        id: test-action--errors
        uses: ./
        continue-on-error: true
        with:
          include: ./__tests__/fixtures/valid/*

      # https://github.com/actions/github-script
      - name: '[validate-book-yaml] Test that errors were found'
        uses: actions/github-script@v7
        env:
          ERRORS: ${{ steps.test-action--errors.outputs.errors }}
        with:
          script: |
            const assert_equal = (value) =>
              require("node:assert/strict").deepEqual(value, true)
            assert_equal(JSON.parse(process.env['ERRORS']).length !== 0)
